### PR TITLE
[1.22] Travis CI: build mate-desktop from 1.22 branch

### PR DESCRIPTION
**Pull request by sc0w**
seems we need to build with mate-desktop 1.22 here

this PR fixes the build in arch and debian:

```
eom-thumbnail.c: In function 'create_thumbnail_from_pixbuf':
eom-thumbnail.c:126:10: warning: implicit declaration of function 'mate_desktop_thumbnail_scale_down_pixbuf'; did you mean 'mate_desktop_thumbnail_path_for_uri'? [-Wimplicit-function-declaration]
  126 |  thumb = mate_desktop_thumbnail_scale_down_pixbuf (pixbuf,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          mate_desktop_thumbnail_path_for_uri
```

### CODE REVIEW

File: .build.yml [hunk 1]
```diff
@@ -59,6 +59,7 @@ requires:
     - git
     - gobject-introspection-devel
     - gtk3-devel
+    - iso-codes-devel
```
Comment (raveit65) [inline .build.yml]: Interesting, so iso-codes-devel is for building mate-desktop here.
