### PR TITLE
Fix building with ImageMagick 7

### PR DESCRIPTION
**Pull request by robert-scheck**
Check for ImageMagick 7 first, then for ImageMagick 6. Original (the reversed) ordering might lead accidentially to `HAVE_IMAGEMAGICK6` with ImageMagick 7.

Build failure at Fedora 38 (with ImageMagick 7): https://koji.fedoraproject.org/koji/buildinfo?buildID=2107065

Successful builds with this pull request applied at:
  - Fedora 38 (with ImageMagick 7): https://koji.fedoraproject.org/koji/taskinfo?taskID=95943021
  - Rocky Linux (with ImageMagick 6): https://koji.fedoraproject.org/koji/taskinfo?taskID=95943024

Pull request results from https://bugzilla.redhat.com/show_bug.cgi?id=2159313 since ImageMagick 7 landed in Fedora Rawhide.

### CODE REVIEW

**Comment by mtasaka** [comment]
This is Fedora side ImageMagick 7 issue. Fedora ImageMagick adds `wand` symlink for old ImageMagick6 compatibility, which confuses current eom ImageMagick detection.

https://src.fedoraproject.org/rpms/ImageMagick/blob/01d0715e042e84c60b00123fe075200c6a64f750/f/ImageMagick.spec#_248

**Comment by mtasaka** [comment]
... and I think this Fedora-specific `wand` symlink creation is imcomplete anyway, because so eom complains about `error: wand/magick_wand.h: No such file or directory`, as reported.

**Comment by raveit65** [comment]
@robert-scheck 
Can you please push that to fedora rawhide branch? I am fine with the fix.

**Comment by robert-scheck** [comment]
@mtasaka, while there might be a specific Fedora issue as well, I personally still would prefer testing on upstream side for a new version _before_ the old version (because there also could be e.g. multiple versions around to cover migration/upgrade scenarios).

@raveit65, done: https://src.fedoraproject.org/rpms/eom/c/8039eaa08ee620f36a4608cc9173fee44de9f1d8?branch=rawhide

**Comment by robert-scheck** [comment]
Any chance for getting this merged?

**Review by lukefromdc — APPROVED** [review]
On my system with Debian Unstable, building EOM works with or without this, with ImageMagick 6, ImageMagick 7, or both installed. Thus this change causes no problems here but I was unable to duplicate the original issue

**Comment by raveit65** [comment]
In fedora 38 with ImageMagick-7.1.1.4-3.fc38.x86_64 installed and using those configure flags.
```
%configure \
   --with-x \
   --disable-schemas-compile \
   --enable-introspection=yes \
   --enable-thumbnailer \
   --without-gdk-pixbuf-thumbnailer
```
configure found ImageMagik but select the wrong ac_header for ImageMagick7
```
checking for MAGICK... yes
checking for wand/MagickWand.h... yes
```
In result building ends up with this error.
```
eom-thumbnailer.c' || echo './'`eom-thumbnailer.c
eom-thumbnailer.c:40:10: fatal error: wand/magick_wand.h: No such file or directory
   40 | #include <wand/magick_wand.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
The right ac_header should be MagickWand/MagickWand.h for ImageMagick7.
The check in configure works fine in f36/37 with ImageMagick-6.9.12.77 installed.
So, i think the check is broken.
Note, you need to build with `--enable-thumbnailer  --without-gdk-pixbuf-thumbnailer` configure flag to see the compiling issue.

**Comment by raveit65** [comment]
> ... and I think this Fedora-specific `wand` symlink creation is imcomplete anyway, because so eom complains about `error: wand/magick_wand.h: No such file or directory`, as reported.

You misunderstood the error message. ImageMagick7 use MagickWand/MagickWand.h which is in ImageMagick-devel-1:7.1.1.4-3.fc38.x86_64 package.
```
[root@mother ~]# ls -l /usr/include/ImageMagick-7/MagickWand/MagickWand.h 
-rw-r--r-- 1 root root 3779 18. Mär 14:13 /usr/include/ImageMagick-7/MagickWand/MagickWand.h
```
The error is caused by wrong ac_header detection. See my post before.

**Comment by raveit65** [comment]
I rechecked this PR with building eom for fedora 36 with ImageMagick-6.9.12.82-1.fc36 which works fine.
So this PR is valid.
